{{- if .Values.contour.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "contour.name" . }}
  namespace: {{ template "contour.namespace" . }}
  labels: {{ include "contour.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.contour.replicaCount }}
  selector:
    matchLabels: {{ include "contour.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.contour.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels: {{ include "contour.labels" . | nindent 8 }}
    spec:
      initContainers:
      - image: "{{ .Values.contour.contour.image.repository }}:{{ .Values.contour.contour.image.tag }}"
        imagePullPolicy: "{{ .Values.contour.contour.image.pullPolicy }}"
        name: envoy-initconfig
        command:
        - contour
        args:
        - bootstrap
        - /config/contour.yaml
        - --statsd-enabled
        volumeMounts:
        - name: contour-config
          mountPath: /config
      containers:
      - image: "{{ .Values.contour.envoy.image.repository }}:{{ .Values.contour.envoy.image.tag }}"
        imagePullPolicy: "{{ .Values.contour.envoy.image.pullPolicy }}"
        name: envoy
        command:
        - envoy
        args:
        - -c
        - /config/contour.yaml
        - --service-cluster
        - cluster0
        - --service-node
        - node0
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8002
          name: statsd
        resources: {{ toYaml .Values.contour.envoy.resources | nindent 10 }}
        volumeMounts:
        - name: contour-config
          mountPath: /config
      - image: "{{ .Values.contour.contour.image.repository }}:{{ .Values.contour.contour.image.tag }}"
        imagePullPolicy: "{{ .Values.contour.contour.image.pullPolicy }}"
        ports:
        - containerPort: 8000
          name: contour
        name: contour
        command:
        - contour
        args:
        - serve
        - --incluster
        - --envoy-http-port=80
        - --debug-http-port=6069
        resources: {{ toYaml .Values.contour.contour.resources | nindent 10 }}
      volumes:
      - name: contour-config
        emptyDir: {}
      dnsPolicy: ClusterFirst
      serviceAccountName: {{ template "contour.name" . }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.contour.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.contour.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.contour.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
