{{- if .Values.contour.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "contour.name" . }}
  namespace: {{ template "contour.namespace" . }}
  labels: {{ include "contour.labels" . | nindent 4 }}
  {{- with .Values.contour.serviceAccountAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "contour.name" . }}
  labels: {{ include "contour.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - nodes
  - pods
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups: ["contour.heptio.com"]
  resources: ["ingressroutes"]
  verbs:
  - get
  - list
  - watch
  - put
  - post
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "contour.name" . }}
  labels: {{ include "contour.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "contour.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "contour.name" . }}
  namespace: {{ template "contour.namespace" . }}
  
{{- end }}
