{{- if .Values.common.ingress.enabled }}
# HTTP Routes
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "flyte.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  annotations:
  {{- with .Values.common.ingress.annotations }}
  {{ toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.common.ingress.httpAnnotations }}
  {{ toYaml . | nindent 4}}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          {{- if eq .Values.common.ingress.controllerType "ALB" }}
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          {{- end }}
          # This is useful only for frontend development
          {{- if .Values.common.ingress.webpackHMR }}
          - path: /__webpack_hmr
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteconsole
                port:
                  number: 80
          {{- end }}
          # Port 87 in FlyteAdmin maps to the redoc container.
          - path: /openapi
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 87
          # NOTE: If you change this, you must update the BASE_URL value in flyteconsole.yaml
          - path: /console
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteconsole
                port:
                  number: 80
          - path: /console/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteconsole
                port:
                  number: 80
          - path: /api
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          - path: /healthcheck
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          - path: /v1/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          # Port 87 in FlyteAdmin maps to the redoc container.
          - path: /openapi/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          - path: /.well-known/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          - path: /login
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          - path: /login/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          - path: /logout
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          - path: /logout/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          - path: /callback
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          - path: /callback/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          - path: /me
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          - path: /config
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
          - path: /config/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 80
      {{- with .Values.common.ingress.host }}
      host: {{ . }}
      {{- end }}
---
# GRPC Routes
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "flyte.name" . }}-grpc
  namespace: {{ template "flyte.namespace" . }}
  annotations:
  {{- with .Values.common.ingress.annotations }}
  {{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.common.ingress.grpcAnnotations }}
  {{- toYaml . | nindent 4}}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          # NOTE: Port 81 in flyteadmin is the GRPC server port for
          # FlyteAdmin.
          - path: /flyteidl.service.AdminService
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 81
          - path: /flyteidl.service.AdminService/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: flyteadmin
                port:
                  number: 81
      {{- with .Values.common.ingress.host }}
      host: {{ . }}
      {{- end }}
{{- end }}