
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "flytepropeller.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flytepropeller.labels" . | nindent 4 }}
  {{- with .Values.flytepropeller.serviceAccountAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "flytepropeller.name" . }}
  labels: {{ include "flytepropeller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - delete
  - patch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - flyte.lyft.com
  resources:
  - flyteworkflows
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
  - post
  - deletecollection

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "flytepropeller.name" . }}
  labels: {{ include "flytepropeller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "flytepropeller.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "flytepropeller.name" . }}
  namespace: {{ template "flyte.namespace" . }}
