{{- if .Values.pytorchoperator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pytorch-operator.name" . }}
  namespace: {{ template "pytorch-operator.namespace" . }}
  labels: {{ include "pytorch-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pytorchoperator.replicaCount }}
  selector:
    matchLabels: {{ include "pytorch-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.pytorchoperator.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels: {{ include "pytorch-operator.labels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.pytorchoperator.image.repository }}:{{ .Values.pytorchoperator.image.tag }}"
        imagePullPolicy: "{{ .Values.pytorchoperator.image.pullPolicy }}"
        name: pytorch-operator
        command:
        - /pytorch-operator.v1
        - --alsologtostderr
        - -v=1
        - --monitoring-port=8443
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources: {{ toYaml .Values.pytorchoperator.resources | nindent 10 }}
      serviceAccountName: {{ template "pytorch-operator.name" . }}
      {{- with .Values.pytorchoperator.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pytorchoperator.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pytorchoperator.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
