{{- if .Values.pytorchoperator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "pytorch-operator.name" . }}
  namespace: {{ template "pytorch-operator.namespace" . }}
  labels: {{ include "pytorch-operator.labels" . | nindent 4 }}
  {{- with .Values.pytorchoperator.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.pytorchoperator.service.type}}
  type: {{ . }}
  {{- end }}
  ports:
  - name: monitoring-port
    port: 8443
    targetPort: 8443
  selector: {{ include "pytorch-operator.selectorLabels" . | nindent 4 }}
{{- end }}
